AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'app/models/coder.rb'
    - 'app/controllers/*'
    - 'spec/routing/*'
    - 'spec/requests/*'
    - 'spec/spec_helper.rb'
    - 'bin/rails'
    - 'bin/rake'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

RegexpLiteral:
  Enabled: false


StringLiterals:
  Enabled: false

AssignmentInCondition:
  Enabled: false

CyclomaticComplexity:
  Enabled: enabled
